### ISSUE TITLE
Descripciones excepciones no consistentes

### ISSUE THREAD

**Issue by casmurdor** [sergiovj2001/GestisimalDocumentation#2]
https://sergiovj2001.github.io/GestisimalDocumentation/excepciones/package-summary.html
Deberían tener una descripción más formal. Por ejemplo: "Captura error del CSV de Almacen"

**Comment by sergiovj2001** [comment]
Buenas compañero, Lourdes a dicho esta tarde en clase que las excepciones deberian empezar con un Si y cuando ocurre la exception
