### ISSUE TITLE
Tildes con error

### ISSUE THREAD

**Issue by casmurdor** [sergiovj2001/GestisimalDocumentation#3]
https://sergiovj2001.github.io/GestisimalDocumentation/gestisimal/package-summary.html
Quitalas hasta que sepamos como solucionarlas
@lmagarin

**Comment by lmagarin** [comment]
@a19camoan @sergiovj2001 Ahora tienes faltas de ortografía. Deberías haberlas dejado y haber cerrado el issue de forma correcta
